---
title: "File_pipeline_Itasca_add_meta"
author: "Sara DeLaurentis"
date: "1/21/2022"
output: html_document
purpose: Attach BASE columns of metadata that will be helpful for analysis.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(stringr)
library(stringi)
library(dplyr)
library(lubridate)
library(glue)

```

## R Markdown

#1. create a dataframe from list of files and list of truncated filenames ("labels").
#2. split the truncated filenames into separate columns
#3. join
```{r }

#SWITCH WORKING DIRECTORY BASED ON DEVICE YOU'RE USING

#setwd("C:/Users/sbaue/coding/R_TEMPRY/Itasca_project_19-21/CLEAN_DATA_copy") #For Home desktop
setwd("C:/Users/sbaue/coding/Itasca_project_19-21/CLEAN_DATA_copy") #For Lenovo Flex

  
  file.names <- list.files(pattern = ".csv", full.names = FALSE) #create list of .csv files
name.data <- file.names %>%  #create dataframe from file.names
  str_replace(".csv", "") %>%  #remove ".csv"
  as_data_frame() #coerce to dataframe
head(name.data)

full.file.names <- list.files(pattern = ".csv", full.names = TRUE) %>% #create dataframe out of list of full file names.
  as_data_frame()

#full.file.names <- list.files(pattern = ".csv", full.names = TRUE) 
#head(full.file.names)

input_df <- cbind(full.file.names, name.data) #bind the two dataframes together
colnames(input_df) <- c("full_paths", "labels")
head(input_df)
tail(input_df)
view(input_df)

#create a dataframe of the "label" elements
add_meta <- function(full_paths,labels){
  
  setwd("C:/Users/sbaue/coding/R_TEMPRY/Itasca_project_19-21/CLEAN_DATA_copy")
  temps <- read.csv(full_paths)
  meta <- labels %>%    
   str_split_fixed("_", n=5) %>% 
    as.data.frame()
  colnames(meta) <- c("site", "rep", "position", "buttonID", "season")
   
    
  head(meta)
  meta$labels <- labels  
    #new dataframe with metadata, setting length equal to the number of rows in the temp_intA, longdate column:
  #  metadata_df <- tibble(labels, treatment, rep, position, buttonID, year, .rows = length(temp_intA$longdate))
    #print(metadata_df)
    
    #bind the metadata_df and temperature data for the final csv output.
    temp_df <- cbind(meta, temps)
    temp_df$unit <- NULL
    temp_df <- temp_df[, c(6,1,2,3,4,5,7,8)]
    
    
      #temporarily change working directory for .csv saving.
    setwd("C:/Users/sbaue/coding/R_TEMPRY/Itasca_project_19-21/CLEAN_DATA_with_meta")
  
    write_csv(temp_df, glue("./meta_{labels}.csv"))}

#add_meta("./C2A_R3_m0surf_i39_2020.csv", "C2A_R3_m0surf_i39_2020") #Test case

pwalk(input_df, add_meta)

```


```{r }



```